/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ejer1.Ejer1;

/**
 *
 * @author 1GDAW12
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mClientes = new javax.swing.JMenu();
        miAltaCliente = new javax.swing.JMenuItem();
        miBajaCliente = new javax.swing.JMenuItem();
        miModificacionCliente = new javax.swing.JMenuItem();
        miConsultaCliente = new javax.swing.JMenuItem();
        mAbogados = new javax.swing.JMenu();
        miAltaAbogado = new javax.swing.JMenuItem();
        miBajaAbogado = new javax.swing.JMenuItem();
        miModificacionAbogados = new javax.swing.JMenuItem();
        miConsultaAbogado = new javax.swing.JMenuItem();
        mCasos = new javax.swing.JMenu();
        miAltaCasos = new javax.swing.JMenuItem();
        miBajaCasos = new javax.swing.JMenuItem();
        miModificacionCasos = new javax.swing.JMenuItem();
        miConsultaCasos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Gabinete de abogados");

        mClientes.setText("Clientes");

        miAltaCliente.setText("Alta");
        miAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaClienteActionPerformed(evt);
            }
        });
        mClientes.add(miAltaCliente);

        miBajaCliente.setText("Baja");
        mClientes.add(miBajaCliente);

        miModificacionCliente.setText("Modificacion");
        mClientes.add(miModificacionCliente);

        miConsultaCliente.setText("Consulta");
        mClientes.add(miConsultaCliente);

        jMenuBar1.add(mClientes);

        mAbogados.setText("Abogados");

        miAltaAbogado.setText("Alta");
        mAbogados.add(miAltaAbogado);

        miBajaAbogado.setText("Baja");
        mAbogados.add(miBajaAbogado);

        miModificacionAbogados.setText("Modificacion");
        mAbogados.add(miModificacionAbogados);

        miConsultaAbogado.setText("Consulta");
        mAbogados.add(miConsultaAbogado);

        jMenuBar1.add(mAbogados);

        mCasos.setText("Casos");

        miAltaCasos.setText("Alta");
        mCasos.add(miAltaCasos);

        miBajaCasos.setText("Baja");
        mCasos.add(miBajaCasos);

        miModificacionCasos.setText("Modificacion");
        miModificacionCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificacionCasosActionPerformed(evt);
            }
        });
        mCasos.add(miModificacionCasos);

        miConsultaCasos.setText("Consulta");
        mCasos.add(miConsultaCasos);

        jMenuBar1.add(mCasos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addGap(0, 212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miModificacionCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificacionCasosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miModificacionCasosActionPerformed

    private void miAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaClienteActionPerformed
        Ejer1.abrirVentanaClientes();
    }//GEN-LAST:event_miAltaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAbogados;
    private javax.swing.JMenu mCasos;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenuItem miAltaAbogado;
    private javax.swing.JMenuItem miAltaCasos;
    private javax.swing.JMenuItem miAltaCliente;
    private javax.swing.JMenuItem miBajaAbogado;
    private javax.swing.JMenuItem miBajaCasos;
    private javax.swing.JMenuItem miBajaCliente;
    private javax.swing.JMenuItem miConsultaAbogado;
    private javax.swing.JMenuItem miConsultaCasos;
    private javax.swing.JMenuItem miConsultaCliente;
    private javax.swing.JMenuItem miModificacionAbogados;
    private javax.swing.JMenuItem miModificacionCasos;
    private javax.swing.JMenuItem miModificacionCliente;
    // End of variables declaration//GEN-END:variables
}
